### ISSUE TITLE
LDAP authenticator: StartTLS support

### ISSUE THREAD

**Issue by poinck** [mumble-voip/mumble-scripts#11]
Does the LDAP authenticator support StartTLS? If so, how this can be configured? If no, is this planned in a future version?

**Comment by hacst** [comment]
Pretty sure it isn't supported at the moment. Likely not that hard to implement this either but as I'm not using LDAP myself and generally know very little about it someone would have to contribute the feature for it to happen.

**Comment by poinck** [comment]
I have looked into it and did some changes to the Script to support StartTLS without requiring a cert. But I have todo further testing.

**Comment by hacst** [comment]
Awesome. Once you like what you have we can land it in the repo.
