### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by Wunderharke** [mumble-voip/mumble-scripts#26]
Is it possible to port those scripts to Python 3, since Python 2 is now officially not supported anymore?

I tried to run the LDAPAuthenticator however, after fixing some syntax with "2to3", python-daemon package seemed to be incompatible between versions for py3 and py2.
I would really appreciate any help :)

**Comment by Kissaki** [comment]
Yes, it should be migrated.

**Comment by Wunderharke** [comment]
Solved by #31
