### ISSUE TITLE
phpBB3 authenticator error 'ERROR not all arguments converted during string formatting`

### ISSUE THREAD

**Issue by SGColdSun** [mumble-voip/mumble-scripts#5]
2015-02-08 03:26:31,248 CRITICAL Unexpected exception caught
2015-02-08 03:26:31,248 ERROR not all arguments converted during string formatting
Traceback (most recent call last):
  File "./phpBB3auth.py", line 375, in newfunc
    return func(*args, **kws)
  File "./phpBB3auth.py", line 466, in authenticate
    cur = threadDB.execute(sql, name)
  File "./phpBB3auth.py", line 188, in execute
    c.execute(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
TypeError: not all arguments converted during string formatting

**Comment by hacst** [comment]
Hi can you tell me a bit more about the environment this is running in? Namely Distro, Python version and MySQLdb python package version might be relevant. The error itself seems pretty strange to me given that this is the usual code-path for the authenticator to take and if the string didn't use all arguments it should fail all the time.

**Comment by SGColdSun** [comment]
Yeah, sorry for not posting the other pertinent information, it was late and I was tired and totally dropped the ball on that.

OS: Ubuntu 14.04.1
Python: 2.7.6
MySQL-python: 1.25

**Comment by hacst** [comment]
Haven't forgotten this. Just very short on time atm. . Might take a while (~1 month) until I'm able to look into this more closely. If someone else wants to investigate in the meantime feel free to do so.

**Comment by hacst** [comment]
@SGColdSun Hi. I pushed a potential fix (823f64a7a51c9dcee06f338f29c308f552c21a8a). Could you try whether it works for you after the update?

**Comment by SGColdSun** [comment]
Everything seems to be in order. Thank you.

**Comment by hacst** [comment]
Awesome. Thanks for reporting.
